name: note_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  auto_route: ^2.4.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_feather_icons: ^2.0.0+1
  flutter_screenutil: ^5.0.0+2
  flutter_staggered_grid_view: ^0.4.1
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
